.TH DECRYPTER 1 "June 2025" "1.0" "Decrypter Manual"
.SH NAME
decrypter \- modular command-line cybersecurity tool for decoding

.SH SYNOPSIS
.B decrypter
[\fISTRING\fR]

.SH DESCRIPTION
.B decrypter
is a modular command-line tool for decoding or reversing strings using various techniques. You can apply multiple decoding methods step-by-step, including Base64, ROT13, and more.
Some techniques even include other options for brute forcing, digit shifting, and even character substitution.

.SH MODULES
.TP
.B base64
Decode Base64-encoded strings.
.TP
.B rot13
Decode ROT13-encoded strings. Includes optional digit shifting and brute-force guessing.
.TP
.B binary
Decode Binary strings. Including strings not made of 0/1's.
.TP
.B hex 
Decode Hex encoded strings.
.TP
.B hexdump
Decode strings from Hexdumps.
.TP
.B url decode
Decode URI/URL percent encodings to raw values.    
.TP
.B morse code
Decode strings of morse code.
.TP
.B xor
Decipher a string with a known key or brute force.
.TP
.B atbash
Substitution cipher that reverses the alphabet.
.TP
.B octal
Decodes octal numbers to decimal and converts from ASCII.

.SH OPTIONS
.TP
.B -f 
File input, replace encrypted string with filename.
.TP
.B -o 
File output, print steps and decrypted strings to an output file.
.TP
.B -m 
List available modules and related info.
.TP
.B -h 
Output help menu.

.SH EXAMPLES
.B decrypter "Ithixcv dji hdbt rdst!"
.RS
Decode Options:
.br
[e]Exit
.br
[1]Base64
.br
[2]ROT13
.br
Choice: 2

.br
Shift digits [y/n]? n
.br
Brute force [y/n]? y

.br
ROT1: Juijydw ekj iecu setu!
.br
ROT25: Hsghwbu cih gcas qcrs!

.br
Enter ROT shift #: 11
.br
ROT11: Testing out some code!

.br
[c] Continue
.br
[r] Revert
.br
[e] Exit

.br
Final string: Testing out some code!
.RE

.SH AUTHOR
Created by GitHub user \fBcDenton1\fR for educational and practical cybersecurity use.

.SH SEE ALSO
base64(1), tr(1), xxd(1)
